### PR TITLE
Switch to eslint

### PR DESCRIPTION
**Pull request by BigBlueHat**
The future is now!

### CODE REVIEW

**Comment by davidlehn** [comment]
Think you can sneak in spaces everywhere?  Nice try! ;-)  Obviously a point of argument, but digitalbazaar has been using a different style for years now and it's hard to justify a change.  Here's the .eslintrc file we try to use elsewhere.  May be able to combine rules.
https://github.com/digitalbazaar/bedrock-dev/blob/master/.eslintrc

I'm not sure we want to use lock files now.  The concept is good but the tools were garbage in the past and they just caused us pain so we have avoided and disabled them everywhere.  Have tools improved recently?

**Comment by BigBlueHat** [comment]
I'll take a look at the new `.eslintrc` and see about adding it to this (and the forthcoming `jsonld-request` PR 😁).

As far as `package-lock.json` goes, I've been adding them based on [NPM's suggested practice](https://docs.npmjs.com/files/package-lock.json): "This file is intended to be committed into source repositories"

It's not be "in the way" in the repos I've added them to--fwiw.

**Comment by BigBlueHat** [comment]
@davidlehn better?

**Comment by davidlehn** [comment]
Switched to eslint in other commits.

**Pull request closed without merging**
